stages:
  - stage: buildstate
    displayName: dotnet build stage
    jobs:
      - job: build
        displayName: dotnet build job
        steps:
          - script: dotnet restore
            displayName: restore
          - script: dotnet build
            displayName: build
          - script: dotnet test
            displayName: test
          - script: dotnet publish
            displayName: publish
